### ISSUE TITLE
ROI config not being saved correcly 

### ISSUE THREAD

**Issue by Woreec** [Am6er/BecqMoni#3]
If you edit ROI config and press save it is not saved after you close and reopen the program

edit ROI config > add BG Difference > press save > close BecqMoni > re-open BecqMoni > edit ROI config > BG Difference not there anymore

it looks like it saves them at ...\Roaming\BecqMoni\config
but loads them from ...\Roaming\BecqMoni\config\ROI

**Comment by Am6er** [comment]
Interesting behavior. What version were used to reproduce this issue?
I tried to reproduce it with debug, but recieved no similar effect..

According [SaveConfig](https://github.com/Am6er/BecqMoni/blob/63fb5fc16a292520788c69c1cae4cabcb4cfc78d/BecquerelMonitor/ROIConfigManager.cs#L215), it uses `configRoi` string, which is defined in ClickOnce deployment case as [\\BecqMoni\\config\\ROI](https://github.com/Am6er/BecqMoni/blob/63fb5fc16a292520788c69c1cae4cabcb4cfc78d/BecquerelMonitor/Package.cs#L120).

**Comment by Woreec** [comment]
the version im using right now is 2023.2.12.2
i will update it to the newest version later today and check if it actually is already fixed
i also might record a video to exacly show what i did

**Comment by Woreec** [comment]
okay so, i updated to 2023.23.21.1 which did not fix it
im using the version from https://amba.cloud/becqmoni/ i updated it through "check updates..." 
after that i uninstalled and deleted all files in roaming of the app and reinstalled but didnt fix it 
i also tried the zip one from github and there it seems to work fine
i guess some kind of config is wrong for the ClickOnce version? is there some place else next to appdata/roaming/.. files get installed/saved that that could cause that? 

https://user-images.githubusercontent.com/46332697/221008695-b7c5ca06-e2d2-4437-be5f-74ad819f373b.mp4

it doesnt really break the software and i know how to work around it so its not to big of a problem to me

**Comment by Am6er** [comment]
Wow! It's really strange behavior. I see..
Let me try to reproduce this behavior more carefully, may be i miss something during investigation. Thank you!

**Comment by Am6er** [comment]
Found it! :) Fix in online update version already deployed 2023.02.24.01, in offline version - soon as i upload it. Thank you Woreec!
